import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

import {
  buildExportFilename,
  EXCEL_EXPORT_COLUMNS,
  formatRowsForExcelExport,
  formatRowsForPdfExport,
} from "@/features/reports/lib/report-export-format";
import type { PendingReportRow } from "@/features/reports/services/pending-report";
import { appConfig } from "@/lib/constants/navigation";

export interface GeneratedReportFile {
  buffer: Buffer;
  filename: string;
  mimeType: string;
}

function buildPdfBuffer(
  rows: PendingReportRow[],
  reportTitle: string,
  generatedBy?: string
): Buffer {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(14);
  doc.setTextColor(30, 64, 120);
  doc.text("DISTRICT COLLECTOR OFFICE", pageWidth / 2, 14, { align: "center" });
  doc.text("KHAIRTHAL-TIJARA", pageWidth / 2, 21, { align: "center" });

  doc.setFontSize(12);
  doc.text("DAK MONITORING REPORT", pageWidth / 2, 29, { align: "center" });

  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text(reportTitle, pageWidth / 2, 35, { align: "center" });

  const generatedDate = new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
  doc.text(`Generated Date: ${generatedDate}`, 14, 42);
  doc.text(`Generated By: ${generatedBy ?? "System"}`, 14, 47);
  doc.text(`Total Records: ${rows.length}`, pageWidth - 14, 42, { align: "right" });

  const tableRows = formatRowsForPdfExport(rows);
  autoTable(doc, {
    startY: 52,
    head: [
      [
        "DAK",
        "Subject",
        "Source",
        "Department",
        "Status",
        "Priority",
        "Due Date",
      ],
    ],
    body: tableRows.map((row) => [
      row.dak_number,
      row.subject,
      row.source_name,
      row.department_name,
      row.status,
      row.priority,
      row.due_date,
    ]),
    styles: { fontSize: 7, cellPadding: 1.5 },
    headStyles: { fillColor: [30, 64, 120], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: 14, right: 14 },
  });

  const finalY =
    (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable
      ?.finalY ?? 52;

  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("Generated from DAK Monitoring System", pageWidth / 2, finalY + 8, {
    align: "center",
  });
  doc.text(appConfig.districtAdministration, pageWidth / 2, finalY + 13, {
    align: "center",
  });

  return Buffer.from(doc.output("arraybuffer"));
}

function buildExcelBuffer(
  rows: PendingReportRow[],
  sheetName: string
): Buffer {
  const formatted = formatRowsForExcelExport(rows);
  const header = EXCEL_EXPORT_COLUMNS.map((col) => col.header);
  const data = formatted.map((row) =>
    EXCEL_EXPORT_COLUMNS.map((col) => row[col.key] ?? "")
  );
  const worksheet = XLSX.utils.aoa_to_sheet([header, ...data]);

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName.slice(0, 31));
  const arrayBuffer = XLSX.write(workbook, {
    bookType: "xlsx",
    type: "array",
  }) as ArrayBuffer;

  return Buffer.from(arrayBuffer);
}

export function generateExcelFile(
  rows: PendingReportRow[],
  filenamePrefix: string,
  sheetName = "Report"
): GeneratedReportFile {
  return {
    buffer: buildExcelBuffer(rows, sheetName),
    filename: buildExportFilename(filenamePrefix, "xlsx"),
    mimeType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  };
}

export function generatePdfFile(
  rows: PendingReportRow[],
  filenamePrefix: string,
  reportTitle: string,
  generatedBy?: string
): GeneratedReportFile {
  return {
    buffer: buildPdfBuffer(rows, reportTitle, generatedBy),
    filename: buildExportFilename(filenamePrefix, "pdf"),
    mimeType: "application/pdf",
  };
}
